### ISSUE TITLE
args missing error didn't handling

### ISSUE THREAD

**Issue by kryr34** [NOOBDY/Homework-ProJYKt#8]
run `get` or `submit` without second args:
```py
Traceback (most recent call last):
  File "./hwp.py", line 76, in <module>
    if f"{args[1]} {args[2]}" == "get all":
IndexError: list index out of range
```

run `submit` without third args:
```py
Traceback (most recent call last):
  File "./hwp.py", line 98, in <module>
    file_path = args[3]
IndexError: list index out of range
```

**Comment by NOOBDY** [comment]
this could be fixed temporarily by using `len(args)` but i will probably implement `argparse` or some library in the future
